### PR TITLE
Test: Add .gov Domains (NERSC, OLCF)

### PR DESCRIPTION
**Pull request by ax3l**
Known to currently cause issues with old CA stores.

cc @vsoch

### CODE REVIEW

**Comment by ax3l** [comment]
@vsoch my CI run here needs manual approval :grin:

**Comment by vsoch** [comment]
Good idea! This will likely currently fail even with the updated container base because the tests are run on the GitHub worker directly, and we don't technically have certifi as a dependency. Should we add it to the test environment? Either way, I'll run it as is now to see the failure so we have a base to start.

**Comment by ax3l** [comment]
Yes, I also thought we run it once, see what fails and then step forward.

**Comment by ax3l** [comment]
What we could do is add a run of the tests from the CI-built docker image.

**Comment by ax3l** [comment]
Ok, the regular test run (on a recent ubuntu) worked. Will rebase now to add a run on the CI docker image

**Comment by vsoch** [comment]
Hey it worked! Go GitHub! lol!

So @ax3l after this merges shall I craft a release for 0.23? The container will actually be built automatically (it's already deployed actually -> https://quay.io/repository/urlstechie/urlchecker?tab=tags), but the pypi version needs to be manual. Since the container is re-buildable I can hold off on the pypi release until you've had a chance to try that with the PR - I'll update the base image to use the new image and ping you on that other PR when it's ready.

**Comment by vsoch** [comment]
I think we're good as is actually, we don't need to run the tests twice. Going to merge here!

**Comment by ax3l** [comment]
But it's not failing :cry: :grin:

**Comment by ax3l** [comment]
All good, I'll test upstream. :ship: 0.23 :heavy_check_mark:

**Comment by vsoch** [comment]
@ax3l looks like this same issue showed up for those domains with your spack packages:

image

**Pull request merged**
