### PR TITLE
Updating tests to use smaller repository

### PR DESCRIPTION
**Pull request by vsoch**
This PR will update the test files to use the smaller repository served under this organization. If it turns out that I need to make additional tweaks, I'll update the PR (I might have missed something or broken a test!)

Signed-off-by: vsoch <vsochat@stanford.edu>

### CODE REVIEW

**Comment by SuperKogito** [comment]
However, it seems that the test-repo must be edited and more links should be added to cover more test cases ;)

**Comment by vsoch** [comment]
Ok, if you want to take a shot we can re-run the tests after, I’m probably done working for today we did a ton!

**Comment by SuperKogito** [comment]
I will go over some stuff but so far it seems to be a smooth transition. I will try to update some external links (docs and others) and you can re-run the tests tomorrow and see what can we improve! 
Great work for today :) Enjoy your Saturday evening ;)

**Comment by vsoch** [comment]
@SuperKogito I'm running tests locally and it's taking a terribly long time - since tests passed here I'm going to merge in favor of speedier development. We can again test with updates to your testing repo in another PR, if that's okay!

**Pull request merged**
