### PR TITLE
reverting back to working client

### PR DESCRIPTION
**Pull request by vsoch**
@SuperKogito I am so upset I couldn't wait to fix this. We need to talk about the proper review and testing that needs to happen before you push breaking changes like this.

Signed-off-by: vsoch <vsochat@stanford.edu>

### CODE REVIEW

**Comment by SuperKogito** [comment]
Yeah you are right, my bad :/ I figured it is actually a bug and not something you did intentionally. That is why I committed directly to the master.  But I still find the previous version a bit confusing so I will wrap my changes in a PR and we can discuss them?

**Comment by vsoch** [comment]
We aren't changing the client to not have command line flags. Per my understanding you want to do:

```
urlchecker check . --cleanup true
```
Perhaps you aren't familiar with flags, but this is just totally wrong.

**Comment by vsoch** [comment]
The correct usage of a flag is:

```bash
urlchecker check . --cleanup
```
It's presence, _period_ indicates true, "yes I want to cleanup."

**Comment by SuperKogito** [comment]
I see. I am sorry, it is my mistake. I was not aware of that :( I will revert the action changes then. and fix the latest release.

**Pull request merged**
