### PR TITLE
Start of urlchecker python module!

### PR DESCRIPTION
**Pull request by vsoch**
This pull request will add automated testing to the current master branch (which is a slightly older version, I realized I needed to put something there). I've worked on the following:

 - the module is organized in a way that I hope is intuitive (described in the README.md) meaning that the client folder serves the entrypoint (client), the core folder contains the same core functions (that are agnostic to cloning, setup, etc.) and the main folder contains helper functions for different integrations (e.g., GitHub).
 - the version.py file handles metadata and dependencies
 - the README.md has a quick walk through to run locally on a folder, or repository. This needs to be replaced by pretty / better docs, but I wanted to have it somewhere for now.
 - GitHub actions are used to run tests
 - a Dockerfile provides a container build, in case anyone wants to use in a container.
 -  a CHANGELOG is added to track major changes corresponding with pypi releases

That's it! I'll update this branch to likely address testing failures.

### CODE REVIEW

**Comment by vsoch** [comment]
@SuperKogito we need to disable travis checks here, this isnt a travis.yml to check (and I'm purposefully staying away because I'm unhappy with the CI across various projects). Could that be possible?

**Comment by SuperKogito** [comment]
I would have expected travis-ci to be more useful here? why are you not satisfied with it? what would be the alternative?

**Comment by vsoch** [comment]
Ah, well in support of not wanting to re-write all the testing, let me see if I can add a .travis.yml.

**Comment by SuperKogito** [comment]
well you can drop it if it is that much of a hustle. I can take care of it if you want ;)

**Comment by vsoch** [comment]
I can do it! I'm too stubborn to not complete the work. Give me another few shots :)

**Comment by SuperKogito** [comment]
lol :P take your time, no pressure ;)

**Comment by vsoch** [comment]
There we go! All green! It was really rather stupid of me, I just forgot to update the way that it's installed, and then I had two bugs (a spelling typo and giving an int to subprocess). I suppose most failures are for reasons like that. We should be good to go now! 

You can see in the README how I was running this locally - it's going to be super easy to wrap this client into a github action that just is a Dockerfile with a shell script to run the same command. What is your pypi username? I can add you to the package as a maintainer. And then after this is merged we can do a release there for 0.0.1 (and do you want to release on GitHub as well?)

Once it's released on pypi, it should be fairly straight forward to update the GitHub actions! I can do this tomorrow if you like, I'm having a lot of fun :)

One quick question - is there any reason to have travis run twice for a PR? The testing already takes a bit of time, and then the user (potentially) needs to wait 1.5X that. Maybe PRs should just be tested, and then merges to master / pushes to random branches ignored?

**Comment by vsoch** [comment]
Merge when you are ready, and let me know how you'd like to move forward! I'd like to suggest:

 - adding you on pypi
 - I'll release 0.0.1 there from master here
 - I'll refactor the action (and open a PR) this weekend to test

Probably no more work for today (other than a release if we merge), almost dinner time! :)

**Comment by SuperKogito** [comment]
great work Vanessa! as usual :clap:  I love the way you structured the project and the separations of some features :+1:  . Everything seems great, so you can merge! 
My username is also [SuperKogito](https://pypi.org/user/SuperKogito/). Your plan seems good, I will let you steer now and try to figure the new structure in the upcoming days :)) Feel free to make all the changes you judge necessary. I am glad that you are enjoying this <3 cuz it is never fun when one is doing it alone. I truly think that without your contributions, I might of gave up on the tool or at least, I wouldn't have been as active as I was :) 

Well you make a good point about travis running twice. Technically, travis is running once on the new branch and once on the PR. I think we should drop the branch run and settle for one run for the PR? if you think it is slow, we can use `pytest-xdist` (like I did initially) but the logs won't be as detailed as now :P

**Comment by vsoch** [comment]
Sounds good! I'll open an issue to address travis. Merging!

**Comment by vsoch** [comment]
https://pypi.org/project/urlchecker/0.0.1/ and you are added!

**Pull request merged**
