### PR TITLE
updating whitelist to be excluded to be more consistent with include

### LINKED ISSUE #48: Minor: misspelling 'whitetlist'
This is a followup to [urlchecker-action #72](https://github.com/urlstechie/urlchecker-action/issues/72): The misspelling "whitetlist" (note extra T) is in the python script.

`check.py` line 66
`README.md` lines 115, 192

I was going to create a PR, but then I thought you might be considering changing "white(_)list(ed)" options to "exclude(d)" to match the change in urlchecker-action, in which case much more than these lines would be getting changed.

As I noted in the title, this is a minor fix, just wanted to follow up since I mentioned it in the original issue and figured out where it was from.

### LINKED ISSUE #49: Update set-env command for docker deploy
https://github.com/urlstechie/urlchecker-python/runs/1826993508?check_suite_focus=true

### PR DESCRIPTION
**Pull request by vsoch**
This pull request will do the following:

 - update all mentions of "white listed" to reference "exclude" or "excluded" (this includes file names as well) (close #48)
 - update the deploy action to not use the now deprecated set-env (close #49)

I'll open a PR alongside this one to update the action - it won't work on the bat because this version of the container won't be deployed, but I should be able to quickly re-run it after we are merged and released here to ensure that the action release is close to this one!

Signed-off-by: vsoch <vsoch@users.noreply.github.com>

### CODE REVIEW

**Comment by SuperKogito** [comment]
@vsoch the PR looks great, but before I continue the review I have a question: 
`white_listed_urls` and `white_listed_patterns` are replaced with `exclude_urls` and `exclude_patterns` but shouldn't we use the adjectives instead of the verbs, so shouldn't the new args be `excluded_urls` and `excluded_patterns`?

**Comment by vsoch** [comment]
@SuperKogito it's not a noun to call them "excluded_urls" it's an action / verb to say "exclude these urls."

**Comment by vsoch** [comment]
It matches what we are currently doing in the action, namely `include_files` and `exclude_files` https://github.com/urlstechie/urlchecker-action/blob/master/action.yml#L60.

**Comment by SuperKogito** [comment]
I think you are right about the `args` used in the terminal, but inside the code I feel like `excluded_...` is more adequate. However using different labels results in lack of consistency. So I wanted to get your input on this since you have more experience with these.

**Comment by vsoch** [comment]
@SuperKogito I think it's fine - the one I chose is shorter, is valid English, and matches what we are using already. I tend to choose actions over nouns, but that's my preference.

**Comment by SuperKogito** [comment]
I think your point about `include_files` settles it ;)

**Comment by vsoch** [comment]
Think of it this way - when the user is writing the action (or calling urlchecker on the command line) they haven't yet included or excluded anything. So it would be weird to say "excluded files" or "included files" to imply they were already included or excluded. On the other hand, if you read verbatim "include these files" for include_files, and "exclude these files" for exclude_files, more akin to a command or action, it feels more correct and reads nicely.

**Review by SuperKogito — APPROVED** [review]
This looks good to me, let's merge :rocket:

**Pull request merged**
