### PR TITLE
Extend add skip check certs

### PR DESCRIPTION
**Pull request by SuperKogito**
This is my PR to https://github.com/urlstechie/urlchecker-python/pull/89#issuecomment-1922502060
This includes:

- Updated Regex
- Commenting of links breaking the tests

I did not update the test workflow as I need time to figure that and test it thoroughly (which I cannot do tonight).

### CODE REVIEW

**Comment by vsoch** [comment]
@SuperKogito but I think you are making progress! I see more checks there than I did here. We will need to go through the failing tests carefully and craft new regular expressions - I don't have time soon but will add to my todo.

**Comment by SuperKogito** [comment]
@vsoch what is happening is that, the worker run task is not being run on the GitHub server, `ERROR - Error running task`. Check the logs of my tests for more infos.
The worker task not being run/ dropped with an error returns empty results lists. Since results list is empty the assert fails. 
Now we have to find out why this happens when tested  online --'

**Comment by vsoch** [comment]
@SuperKogito that just means that there is an error within the task. The way to debug is to run the same in serial, likely on a local machine so you can IPython.embed() and test why there are no match results for Urls (there should be) and then figure out how to update the regexes.

**Comment by SuperKogito** [comment]
@vsoch I don't think that is the issue. Check my fifth and last commits above. I already tested in serial mode online and this fails (the same passes locally). The REGEX might need a revision but this is not a REGEX issue from what I see.  The latest issue proves that. You can see the extracted URLs being correct, unless I am missing something here.

**Comment by vsoch** [comment]
I think we are good here and figured it out in https://github.com/urlstechie/urlchecker-python/pull/89. Thanks for your help here @SuperKogito !

**Pull request closed without merging**
